services:
  authservice:
    build: ./AuthService
    env_file:
      - ./AuthService/.env # list item, not key-value
    ports:
      - "5000:5000"
    depends_on:
      - auth_db

  auth_db:
    image: mysql:8
    env_file:
      - ./AuthService/.env # load same env for DB
    ports:
      - "3306:3306"
    volumes:
      - auth_db_data:/var/lib/mysql

volumes:
  auth_db_data:
