name: Build, Test & Deploy AuthService

on:
  push:
    branches: [dev]
    paths:
      - "backend/AuthService/**"
      - "backend/AuthService.Tests/**"
  pull_request:
    branches: [dev]
    paths:
      - "backend/AuthService/**"
      - "backend/AuthService.Tests/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  # Build & Test job
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./backend/AuthService/AuthService.csproj

      - name: Build
        run: dotnet build ./backend/AuthService/AuthService.csproj --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ./backend/AuthService.Tests/AuthService.Tests.csproj --no-build --logger "junit;LogFilePath=./backend/AuthService.Tests/TestResults.xml"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./backend/AuthService.Tests/TestResults.xml

      - name: Test Reporter
        uses: dorny/test-reporter@v2
        with:
          name: AuthService Tests
          path: ./backend/AuthService.Tests/TestResults.xml
          reporter: junit

  # 2️ Build Docker & Push to GHCR
  docker-build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/nayanthanethsara/authservice:latest
          context: ./backend/AuthService
          file: ./backend/AuthService/Dockerfile

  # Deploy to Azure
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.THEKADEAUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.THEKADEAUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.THEKADEAUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name thekade-authservice \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ghcr.io/nayanthanethsara/authservice:latest
