name: CI/CD Pipeline

on:
  push:
    branches:
      - dev # ✅ runs only on dev branch
  pull_request:
    branches:
      - dev # ✅ optional: also run for PRs into dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./AuthService

      - name: Build
        run: dotnet build ./AuthService --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./AuthService --no-build --verbosity normal
