name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/AuthService

      - name: Build
        run: dotnet build ./backend/AuthService --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./backend/AuthService.Tests --no-build --verbosity normal
