name: Trigger auto deployment for thekade-authservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/thekade-authservice-AutoDeployTrigger-fc7890a6-f902-4be1-8cf0-36dc4ee99924.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.THEKADEAUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.THEKADEAUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.THEKADEAUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.THEKADEAUTHSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.THEKADEAUTHSERVICE_REGISTRY_PASSWORD }}
          containerAppName: thekade-authservice
          resourceGroup: theKadeNalanda
          imageToBuild: ghcr.io/thekade-authservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


